version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.minecraftforge.gradle:ForgeGradle
    versions:
    - 4.0.13
    - 4.0.15
    - 4.0.16
    - 4.0.17
    - 4.0.19
    - 4.0.23
    - 4.1.1
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.1.7
  - dependency-name: junit:junit
    versions:
    - 4.13.1
